{% set name = "ezconda" %}
{% set version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ezconda-{{ version }}.tar.gz
  sha256: 6fdba639fdafa2559e321eb5abb96b9c6fc803e492d5b961fb6d042befd5cad7

build:
  number: 0
  noarch: python
  entry_points:
    - ezconda = ezconda.main:app
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - poetry
    - python >=3.7
  run:
    - python >=3.7
    - pyyaml >=5.4.1
    - rich >=10.11.0
    - typer >=0.4.0
    - tomlkit >=0.9.0
    - importlib_metadata >=4.11.4
    - conda >=4.8
    - mamba

test:
  imports:
    - ezconda
    - ezconda.experimental
  commands:
    - pip check
    - ezconda --help
  requires:
    - pip

about:
  home: https://github.com/SarthakJariwala/ezconda
  summary: Create, Manage, Re-create conda environments & specifications with ease.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SarthakJariwala
